[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_crowdfund_tutorial = "2N6QZDfjFzCKYVJ9pELvv3S5y1KVxxDTyzDuyAdv5RaV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
